### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ColinGilbert** [Lunarsong/NativeAndroid_03#1]
Hi,

I'd really like to incorporate these excellent Android NDK templates (with accreditation, of course) into my own work, but the code has no license. Could you place it under a (non-viral) liberal license? BSD, MIT, or zlib/png would be perfect, but I would be quite open to backporting fixes/improvements if required to do so.

Thanks!
PS: I found your LOD'ing articles quite enlightening,

**Comment by Lunarsong** [comment]
Hi Colin, sorry for the delayed response! I'll set a license now :)

Glad you like my articles!

**Comment by ColinGilbert** [comment]
Thanks, that's wonderful! Another thing that I noticed as I tried to contact you was that you're head of developer relations at Google. I'm sorry for being so abrupt, but will Google Code upload a snapshot to Github or Bitbucket?

I'm really concerned about the loss of open-source heritage due to such an extinction, and as a developer keen on open source it would be really great if you could get the people in charge to save what we have before it goes into darkness.

**Comment by Lunarsong** [comment]
Hey Colin! I am not at all head of developer relations, I am part of the wonderful team of people in dev-rel working on game related technologies :)

As for porting from Google Code to GitHub, see here:
https://code.google.com/export-to-github/
